### CREATE Category 1
POST http://localhost:3000/api/categories
Content-Type: application/json

{
  "name": "Cinturón Negro"
}

### CREATE Category 2
POST http://localhost:3000/api/categories
Content-Type: application/json

{
  "name": "Cinturón Blanco"
}

### GET Categories
GET http://localhost:3000/api/categories

### GET Category by ID
# Reemplaza 1 con el ID de la categoría que desees ver
GET http://localhost:3000/api/categories/1

### UPDATE Category
# Reemplaza 1 con el ID de la categoría que desees actualizar
PUT http://localhost:3000/api/categories/1
Content-Type: application/json

{
  "name": "Cinturón Negro Avanzado"
}

### DELETE Category
# Reemplaza 1 con el ID de la categoría que desees eliminar
DELETE http://localhost:3000/api/categories/2