### CREATE User (ADMIN)
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "email": "admin100@example.com",
  "username": "adminUser",
  "password": "123456",
  "roleId": 1
}

### CREATE User (COACH)
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "email": "coach100@example.com",
  "username": "coachUser",
  "password": "123456",
  "roleId": 2
}

### CREATE User (STUDENT)
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "email": "student100@example.com",
  "username": "studentUser",
  "password": "123456",
  "roleId": 3
}

### GET All Users
GET http://localhost:3000/api/users

### GET User by ID
GET http://localhost:3000/api/users/1

### UPDATE User
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
  "username": "superAdmin",
  "password": "newPassword123",
  "roleId": 2
}

### DELETE User
DELETE http://localhost:3000/api/users/1